### ISSUE TITLE
Add a `--noLaunchBrowser` option 

### ISSUE THREAD

**Issue by deflaux** [googlegenomics/elasticluster#6]
for oauth flows in headless scenarios. . .  or make that the default.

**Comment by mbookman** [comment]
Turns out this feature already exists - we should highlight it in the documentation, particular for the case where one might run Elasticluster on a GCE instance.

You just need to add the value:

```
noauth_local_webserver=True
```

to your "cloud" configuration in ~/.elasticluster/config.

**Comment by mbookman** [comment]
Now documented here:

http://googlegenomics.readthedocs.org/en/latest/use_cases/setup_gridengine_cluster_on_compute_engine/index.html#running-elasticluster-on-a-remote-workstation
